### PR TITLE
Hash saved files if no block id is provided

### PR DESCRIPTION
**Pull request by sHermanGriffiths**
# Describe Your Changes
Reinstate downloaded file content hashing

# How Did You Test It
N/A

### CODE REVIEW

**Comment by johndgiese** [comment]
Hey @sHermanGriffiths why is this change required?

**Comment by sHermanGriffiths** [comment]
> Hey @sHermanGriffiths why is this change required? Why aren't we able to provide a block id?

Because the images we use the urls from Notion for are Page properties

**Comment by sHermanGriffiths** [comment]
> Hey @sHermanGriffiths why is this change required? Why aren't we able to provide a block id?

@johndgiese Because the images we use the urls from Notion for are Page properties

**Review by johndgiese — APPROVED** [review]
Please add a comment explaining the situation when `block_id` would legitametly be None.

**Pull request merged**
